version: '3'
services:
  #Nginx Service
  notify-webserver-nginx:
    image: nginx:alpine
    container_name: notify-webserver-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "1080:80"
      - "1443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
  #-----------------------------------------------------------------------------
  #PHP Service
  notify-phpfpm:
    image: php:8-fpm
    container_name: notify-phpfpm
    build:
      context: .
      dockerfile: ./php/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
  # ============================================================================
  composer:
    restart: 'no'
    image: composer
    command: composer install --ignore-platform-reqs
    volumes:
      - ./lumen:/app
#-------------------------------------------------------------------------------
#Docker Networks
networks:
  app-network:
    name: db_net
    driver: bridge
    # external: true
